# AI监控系统配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug" # debug, release, test
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_bytes: 1048576

# 数据库配置
database:
  driver: sqlite
  host: localhost
  port: 3306
  name: data/aimonitor.db
  user: root
  password: 870629
  ssl_mode: disable
  max_connections: 100
  max_idle_conns: 10
  conn_max_lifetime: 1h
  conn_max_idle_time: 30m
  timeout: 30s
  read_timeout: 30s
  write_timeout: 30s

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s
  idle_check_frequency: 60s

# JWT配置
jwt:
  secret_key: "your-secret-key-change-in-production"
  access_token_expiry: 24h
  refresh_token_expiry: 168h # 7 days
  issuer: "ai-monitor"

# Prometheus配置
prometheus:
  url: "http://localhost:9090"
  timeout: 30s
  max_samples: 50000000
  query_timeout: 2m
  
# Elasticsearch配置
elasticsearch:
  addresses:
    - "http://localhost:9200"
  username: ""
  password: ""
  cloud_id: ""
  api_key: ""
  timeout: 30s
  max_retries: 3
  retry_backoff: 100ms

# AI模型配置
ai_models:
  openai:
    api_key: "your-openai-api-key"
    base_url: "https://api.openai.com/v1"
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 4000
    timeout: 60s
    rate_limit:
      requests_per_minute: 60
      tokens_per_minute: 90000
    cost_limit:
      daily_limit: 100.0
      monthly_limit: 1000.0
      alert_threshold: 0.8
  
  claude:
    api_key: "your-claude-api-key"
    base_url: "https://api.anthropic.com"
    model: "claude-3-sonnet-20240229"
    temperature: 0.7
    max_tokens: 4000
    timeout: 60s
    rate_limit:
      requests_per_minute: 60
      tokens_per_minute: 90000
    cost_limit:
      daily_limit: 100.0
      monthly_limit: 1000.0
      alert_threshold: 0.8

# 邮件配置
email:
  smtp:
    host: "smtp.gmail.com"
    port: 587
    username: "your-email@gmail.com"
    password: "your-app-password"
    from: "AI Monitor <your-email@gmail.com>"
    use_tls: true
  templates:
    alert_subject: "[{{.Severity}}] {{.AlertName}} - {{.Status}}"
    alert_body: "alert_notification.html"

# 告警配置
alerting:
  evaluation_interval: 30s
  notification_timeout: 30s
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h
  max_alerts_per_group: 100
  
  # 告警收敛配置
  aggregation:
    enabled: true
    time_window: 5m
    max_count: 5
    group_by:
      - "alertname"
      - "instance"
      - "severity"

# 数据采集配置
collector:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s
  
  # 平台配置
  platforms:
    windows:
      enabled: true
      exporters:
        - "windows_exporter"
        - "wmi_exporter"
      metrics:
        - "cpu"
        - "memory"
        - "disk"
        - "network"
        - "services"
    
    linux:
      enabled: true
      exporters:
        - "node_exporter"
        - "systemd_exporter"
      metrics:
        - "cpu"
        - "memory"
        - "disk"
        - "network"
        - "processes"
    
    macos:
      enabled: true
      exporters:
        - "darwin_exporter"
      metrics:
        - "cpu"
        - "memory"
        - "disk"
        - "network"
    
    esxi:
      enabled: true
      exporters:
        - "vmware_exporter"
      metrics:
        - "vm_cpu"
        - "vm_memory"
        - "vm_disk"
        - "vm_network"
        - "datastore"

# 日志配置
logging:
  level: "info" # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, file
  file_path: "logs/ai-monitor.log"
  max_size: 100 # MB
  max_backups: 10
  max_age: 30 # days
  compress: true

# 安全配置
security:
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Origin"
      - "Content-Type"
      - "Accept"
      - "Authorization"
    expose_headers:
      - "Content-Length"
    allow_credentials: true
    max_age: 12h
  
  rate_limit:
    enabled: true
    requests_per_minute: 1000
    burst_size: 100
    
  encryption:
    key: "your-encryption-key-32-characters"
    algorithm: "AES-256-GCM"

# 监控和健康检查
monitoring:
  health_check:
    enabled: true
    interval: 30s
    timeout: 10s
    endpoints:
      - "/health"
      - "/metrics"
  
  metrics:
    enabled: true
    path: "/metrics"
    namespace: "ai_monitor"
    
  tracing:
    enabled: false
    jaeger_endpoint: "http://localhost:14268/api/traces"
    service_name: "ai-monitor"
    
# 缓存配置
cache:
  default_ttl: 300s # 5 minutes
  cleanup_interval: 600s # 10 minutes
  max_size: 1000
  
  # 特定缓存配置
  configs:
    metrics:
      ttl: 60s
      max_size: 10000
    alerts:
      ttl: 30s
      max_size: 5000
    users:
      ttl: 3600s # 1 hour
      max_size: 1000
    ai_analysis:
      ttl: 1800s # 30 minutes
      max_size: 500

# 特性开关
feature_flags:
  ai_analysis: true
  failure_prediction: true
  auto_remediation: false
  advanced_analytics: true
  real_time_streaming: true
  multi_tenant: false
  
# 开发环境配置
development:
  debug: true
  hot_reload: true
  mock_ai: false
  seed_data: true
  profiling: true
  
# 生产环境配置
production:
  debug: false
  hot_reload: false
  mock_ai: false
  seed_data: false
  profiling: false