server:
  host: "localhost"
  port: 8080
  api_key: "your-api-key-here"
  ssl: false

agent:
  name: "Nginx Monitor Agent"
  type: "nginx"
  interval: 30s
  timeout: 10s

metrics:
  enabled: true
  interval: 30s

logging:
  level: "info"
  file: "nginx-agent.log"

# Nginx特定配置
nginx:
  status_url: "http://localhost/nginx_status"  # nginx status模块URL
  config_path: "/etc/nginx/nginx.conf"         # nginx配置文件路径
  access_log_path: "/var/log/nginx/access.log" # 访问日志路径
  error_log_path: "/var/log/nginx/error.log"   # 错误日志路径
  pid_file: "/var/run/nginx.pid"               # PID文件路径
  
  # 监控配置
  monitoring:
    parse_logs: true          # 是否解析日志文件
    log_format: "combined"    # 日志格式
    max_log_lines: 1000       # 每次读取的最大日志行数
    
  # 上游服务器监控
  upstream:
    enabled: true
    status_url: "http://localhost/upstream_status"  # upstream status URL
    
  # SSL监控
  ssl:
    enabled: true
    check_certificates: true   # 是否检查SSL证书
    cert_expiry_warning_days: 30  # 证书过期警告天数